### ISSUE TITLE
Can't get it to work ...

### ISSUE THREAD

**Issue by oosterhagen** [a-nom-ali/inkscape-comfyui-extension#3]
### Discussed in https://github.com/a-nom-ali/inkscape-comfyui-extension/discussions/2

<div type='discussions-op-text'>

<sup>Originally posted by **oosterhagen** December  1, 2024</sup>
ComfyUI works.

Inkcape works

Extension files (.py & .inx) copied to the user extensions folder.

But when activated, I get the following errror:

---------------------------------
Traceback (most recent call last):
  File "C:\Users\Michiel\AppData\Roaming\inkscape\extensions\org.inkscape.extension.33353\comfyui_extension.py", line 851, in <module>
    ComfyUIExtension().run()
  File "C:\Users\Michiel\Desktop\inkscape 1.4 build2024-10-20\share\inkscape\extensions\inkex\base.py", line 252, in run
    self.save_raw(self.effect())
                  ^^^^^^^^^^^^^
  File "C:\Users\Michiel\AppData\Roaming\inkscape\extensions\org.inkscape.extension.33353\comfyui_extension.py", line 372, in effect
    workflow_json = self.populate_workflow(workflow_json)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michiel\AppData\Roaming\inkscape\extensions\org.inkscape.extension.33353\comfyui_extension.py", line 544, in populate_workflow
    workflow_json[positive_id]["inputs"]["text"] \
    ~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: '20'
---------------------------------
I guess I've overlooked something in step 3: 
"You need to find the correct IDs in the JSON file and set those in the IDs tab.

    These IDs will differ from what you see in your normal (non-api) workflow in ComfyUI, so remember to check.
    Defaults for these ID's have been set up to match those in the following folder:

        assets/workflows/api
        "
That puzzels me.

</div>

**Comment by a-nom-ali** [comment]
Hi @oosterhagen,

Thanks for reporting this issue and for trying out the extension!

I can see where the confusion might come from, and I’ll update the README.md to clarify. 

For now, here’s a short explanation followed by a more detailed technical walkthrough.

# Short Answer

If you’re using the workflows included in assets/workflows/api without modifications, select the default workflows in the Comfy tab of the extension. The IDs should already be pre-configured and work out of the box. I'm looking into how to have the default workflows preconfigured as well.

# Longer Answer

It seems the confusion might stem from a couple of advanced ComfyUI settings, which I’ll explain:

## Settings

###	Enabling Dev Mode

To view the “Save (API Format)” button, you need to enable Dev Mode in ComfyUI:

* Click the gear icon to open ComfyUI Settings.
* Under the Comfy section, enable Dev Mode Options.
* You’ll now see a “Save (API Format)” button in the interface. This saves workflows in a format compatible with APIs, stripping visual/layout data and recalculating node IDs.

### Displaying Node IDs with Badges

To display node IDs directly on the workflow:
* In ComfyUI Settings, go to the LiteGraph section.
* Under the Node subsection, set Node ID Badge Mode to “Show All”.
* Node ID badges will now appear in the top-right corner of each node, e.g., #21.

## API Workflow Format and IDs

When a workflow is saved in API format, node IDs are recalculated, and these might not match the original IDs in the regular workflow. The extension expects workflows in the API format.

To resolve the KeyError: '20' issue:
* Open the API format workflow in ComfyUI to view the new node IDs, or inspect the JSON file in a text editor.
* Update the IDs in the IDs tab of the extension to match the node IDs in the API format.

### Why This Matters

The JSON files in assets/workflows/api are pre-saved in API format and should work seamlessly with the extension as long as ComfyUI is running and the models for the workflows have been downloaded. If you want to use custom workflows:

* Save them as API format using the “Save (API Format)” button.
* Update the extension’s IDs tab to align with the new IDs from the API format JSON.

This should fix the issue, but if you have any further questions, feel free to ask. Thanks for your patience while I improve the documentation and extension!
